"""Initial migration

Revision ID: f45130f7a0c2
Revises: 
Create Date: 2025-05-03 09:43:49.900937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45130f7a0c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.String(length=200), nullable=False),
    sa.Column('image_filename', sa.String(length=100), nullable=True),
    sa.Column('choice1', sa.String(length=100), nullable=True),
    sa.Column('choice2', sa.String(length=100), nullable=True),
    sa.Column('choice3', sa.String(length=100), nullable=True),
    sa.Column('correct_answer', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('question')
    # ### end Alembic commands ###
